//Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//Notification
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

//Auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const USER_LOADING  = 'USER_LOADING';
export const USER_LOADED  = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH-ERROR';
export const SIGNOUT =  'SIGNOUT';

//Profile
export const EDIT_PROFILE_BEGIN = 'EDIT_PROFILE_BEGIN';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

//Posts
export const POSTS_LOADING = 'POSTS_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const ADD_POST_BEGIN = 'ADD_POST_BEGIN';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';
export const REMOVE_POST_BEGIN = 'REMOVE_POST_BEGIN';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_FAILURE = 'REMOVE_POST_FAILURE';
export const EDIT_FILTER_POST_BEGIN = 'EDIT_FILTER_POST_BEGIN';
export const EDIT_FILTER_POST_SUCCESS = 'EDIT_FILTER_POST_SUCCESS';
export const EDIT_FILTER_POST_FAILURE = 'EDIT_FILTER_POST_FAILURE';
export const NEW_POST_FROM_SOCKET = 'NEW_POST_FROM_SOCKET';
export const NEW_COMMENT_FROM_SOCKET = 'NEW_COMMENT_FROM_SOCKET';

//Comments
export const ADD_COMMENT_BEGIN = 'ADD_COMMENT_BEGIN';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const REMOVE_COMMENT_BEGIN = 'REMOVE_COMMENT_BEGIN';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_FAILURE = 'REMOVE_COMMENT_FAILURE';

//Pages
export const SET_GET_POST_PAGE = 'SET_GET_POST_PAGE';

export const REINITIALIZE_STATE = 'REINITIALIZE_STATE';

//Documentation
export const GET_CATEGORY_LIST_BEGIN = 'GET_CATEGORY_LIST_BEGIN';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILURE = 'GET_CATEGORY_LIST_FAILURE';
export const GET_CATEGORY_FILE_LIST_BEGIN  = 'GET_CATEGORY_FILE_LIST_BEGIN';
export const GET_CATEGORY_FILE_LIST_SUCCESS = 'GET_CATEGORY_FILE_LIST_SUCCESS';
export const GET_CATEGORY_FILE_LIST_FAILURE = 'GET_CATEGORY_FILE_LIST_FAILURE';
export const GET_FILE_BEGIN  = 'GET_FILE_BEGIN';
export const GET_FILE_SUCCESS = 'GET_FILE_SUCCESS';
export const GET_FILE_FAILURE = 'GET_FILE_FAILURE';

export const ADD_CATEGORY_BEGIN = 'ADD_CATEGORY_BEGIN';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const EDIT_CATEGORY_NAME_BEGIN = 'EDIT_CATEGORY_NAME_BEGIN';
export const EDIT_CATEGORY_NAME_SUCCESS = 'EDIT_CATEGORY_NAME_SUCCESS';
export const EDIT_CATEGORY_NAME_FAILURE = 'EDIT_CATEGORY_NAME_FAILURE';
export const REMOVE_CATEGORY_BEGIN = 'REMOVE_CATEGORY_BEGIN';
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY_FAILURE = 'REMOVE_CATEGORY_FAILURE';

export const CREATE_FILE_BEGIN = 'CREATE_FILE_BEGIN';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const CREATE_FILE_FAILURE = 'CREATE_FILE_FAILURE';
export const EDIT_FILE_BEGIN = 'EDIT_FILE_BEGIN';
export const EDIT_FILE_SUCCESS = 'EDIT_FILE_SUCCESS';
export const EDIT_FILE_FAILURE = 'EDIT_FILE_FAILURE';
export const REMOVE_FILE_BEGIN = 'REMOVE_FILE_BEGIN';
export const REMOVE_FILE_SUCCESS = 'REMOVE_FILE_SUCCESS';
export const REMOVE_FILE_FAILURE = 'REMOVE_FILE_FAILURE';

export const GET_DELETED_FILES_BEGIN = 'GET_DELETED_FILES_BEGIN';
export const GET_DELETED_FILES_SUCCESS = 'GET_DELETED_FILES_SUCCESS';
export const GET_DELETED_FILES_FAILURE = 'GET_DELETED_FILES_FAILURE';
export const RESTORE_FILE_BEGIN = 'RESTORE_FILE_BEGIN';
export const RESTORE_FILE_SUCCESS = 'RESTORE_FILE_SUCCESS';
export const RESTORE_FILE_FAILURE = 'RESTORE_FILE_FAILURE';

export const GET_DELETED_CATEGORIES_BEGIN = 'GET_DELETED_CATEGORIES_BEGIN';
export const GET_DELETED_CATEGORIES_SUCCESS = 'GET_DELETED_CATEGORIES_SUCCESS';
export const GET_DELETED_CATEGORIES_FAILURE = 'GET_DELETED_CATEGORIES_FAILURE';
export const RESTORE_CATEGORY_BEGIN = 'RESTORE_CATEGORY_BEGIN';
export const RESTORE_CATEGORY_SUCCESS = 'RESTORE_CATEGORY_SUCCESS';
export const RESTORE_CATEGORY_FAILURE = 'RESTORE_CATEGORY_FAILURE';