//Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//Auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const USER_LOADING  = 'USER_LOADING';
export const USER_LOADED  = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH-ERROR';
export const SIGNOUT =  'SIGNOUT';

//Posts
export const POSTS_LOADING = 'POSTS_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const ADD_POST_BEGIN = 'ADD_POST_BEGIN';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';
export const REMOVE_POST_BEGIN = 'REMOVE_POST_BEGIN';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_FAILURE = 'REMOVE_POST_FAILURE';
export const CHANGE_FILTER_POST_BEGIN = 'CHANGE_FILTER_POST_BEGIN';
export const CHANGE_FILTER_POST_SUCCESS = 'CHANGE_FILTER_POST_SUCCESS';
export const CHANGE_FILTER_POST_FAILURE = 'CHANGE_FILTER_POST_FAILURE';

//Comments
export const ADD_COMMENT_BEGIN = 'ADD_COMMENT_BEGIN';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const REMOVE_COMMENT_BEGIN = 'REMOVE_COMMENT_BEGIN';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_FAILURE = 'REMOVE_COMMENT_FAILURE';

//Pages
export const SET_GET_POST_PAGE = 'SET_GET_POST_PAGE';

export const REINITIALIZE_STATE = 'REINITIALIZE_STATE';

//Documentation
export const GET_CATEGORY_LIST_BEGIN = 'GET_CATEGORY_LIST_BEGIN';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILURE = 'GET_CATEGORY_LIST_FAILURE';
export const GET_CATEGORY_FILE_LIST_BEGIN  = 'GET_CATEGORY_FILE_LIST_BEGIN';
export const GET_CATEGORY_FILE_LIST_SUCCESS = 'GET_CATEGORY_FILE_LIST_SUCCESS';
export const GET_CATEGORY_FILE_LIST_FAILURE = 'GET_CATEGORY_FILE_LIST_FAILURE';
export const GET_FILE_BEGIN  = 'GET_FILE_BEGIN';
export const GET_FILE_SUCCESS = 'GET_FILE_SUCCESS';
export const GET_FILE_FAILURE = 'GET_FILE_FAILURE';
export const ADD_CATEGORY_BEGIN = 'ADD_CATEGORY_BEGIN';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const CREATE_FILE_BEGIN = 'CREATE_FILE_BEGIN';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const CREATE_FILE_FAILURE = 'CREATE_FILE_FAILURE';
export const EDIT_FILE_BEGIN = 'EDIT_FILE_BEGIN';
export const EDIT_FILE_SUCCESS = 'EDIT_FILE_SUCCESS';
export const EDIT_FILE_FAILURE = 'EDIT_FILE_FAILURE';